version: '2'
services:
  microservice:
    build: .
    image: cloud-native-go-app
    environment:
      - PORT=1234
    ports:
      - "1234:1234"
  nginx:
    image: "nginx:1.11.9"
    ports:
      - "8080:80"
    links:
      - microservice
