apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-native-go
  labels:
    app: cloud-native-go
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: cloud-native-go
        tier: service
    spec:
      containers:
      - name: cloud-native-go
        image: frescoraja/cloud-native-go-app
        ports:
        - containerPort: 1234
        env:
        - name: PORT
          value: "1234"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 1234
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 1234
          initialDelaySeconds: 5
          timeoutSeconds: 5
